[package]
name = "trie-alg"
version = "0.4.0"
edition = "2021"
description = "Trie implementation"
license= "GPL-2.0-or-later"
auther = ["adip1343"]
keywords = ["trie", "string", "algorithm", "collection", "data-structure"]

[dependencies]
